name: Export PostgreSQL database to SQLite
on:
  workflow_dispatch:
jobs:
  export-postgresql-database-to-sqlite:
    name: Export PostgreSQL database to SQLite
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGDATABASE: demo
      PGUSERNAME: demo
      PGPASSWORD: demo
    steps:
      - name: Start preinstalled PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create database user
        run: |
          sudo -u postgres psql --command="CREATE USER demo PASSWORD 'demo'" --command="\du"
      - name: Create database and allow user
        run: |
          sudo -u postgres createdb --owner=demo demo
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: '7'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: pnpm start
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install 'db-to-sqlite[postgresql]'
      - run: db-to-sqlite "postgresql://demo:demo@localhost/demo" database.db --all
      - run: ls -l database.db
